FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY ["MessageBroker.Consumers/MessageBroker.Consumers.csproj","MessageBroker.Consumers/"]
COPY ["TravelAgency.HotelService/TravelAgency.HotelService.csproj","TravelAgency.HotelService/"]
RUN dotnet restore "MessageBroker.Consumers/MessageBroker.Consumers.csproj"
RUN dotnet restore "TravelAgency.HotelService/TravelAgency.HotelService.csproj"

COPY . ./
RUN dotnet publish "TravelAgency.HotelService/TravelAgency.HotelService.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet","TravelAgency.HotelService.dll"]

