FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY ["MessageBroker.Consumers/MessageBroker.Consumers.csproj","MessageBroker.Consumers/"]
COPY ["TravelAgency.TravelService/TravelAgency.TravelService.csproj","TravelAgency.TravelService/"]

RUN dotnet restore "MessageBroker.Consumers/MessageBroker.Consumers.csproj"
RUN dotnet restore "TravelAgency.TravelService/TravelAgency.TravelService.csproj"

COPY . ./
RUN dotnet publish "TravelAgency.TravelService/TravelAgency.TravelService.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ADD TravelAgency.TravelService/Images Images/
ENTRYPOINT ["dotnet","TravelAgency.TravelService.dll"]

