FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY ["MessageBroker.Consumers/MessageBroker.Consumers.csproj","MessageBroker.Consumers/"]
COPY ["TravelAgency.BookingService/TravelAgency.BookingService.csproj","TravelAgency.BookingService/"]
RUN dotnet restore "MessageBroker.Consumers/MessageBroker.Consumers.csproj"
RUN dotnet restore "TravelAgency.BookingService/TravelAgency.BookingService.csproj"

COPY . ./
RUN dotnet publish "TravelAgency.BookingService/TravelAgency.BookingService.csproj" -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet","TravelAgency.BookingService.dll"]

