CREATE TABLE public."HotelOffers" (
    "Id" uuid NOT NULL,
    "ExpirationDate" timestamp without time zone NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "HotelId" integer NOT NULL,
    "HotelRoomId" integer NOT NULL,
    "NumberOfRooms" integer NOT NULL,
    "OfferStarted" boolean NOT NULL,
    "OfferFinished" boolean NOT NULL,
    "Price" double precision
);


ALTER TABLE public."HotelOffers" OWNER TO postgres;

--
-- Name: HotelReviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."HotelReviews" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "HotelId" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    "Comment" text
);


ALTER TABLE public."HotelReviews" OWNER TO postgres;

--
-- Name: HotelReviews_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."HotelReviews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HotelReviews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: HotelRooms; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."HotelRooms" (
    "Id" integer NOT NULL,
    "HotelId" integer NOT NULL,
    "RoomTypeId" integer NOT NULL,
    "Capacity" integer NOT NULL
);


ALTER TABLE public."HotelRooms" OWNER TO postgres;

--
-- Name: HotelRooms_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."HotelRooms" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."HotelRooms_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Hotels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Hotels" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "CityId" integer NOT NULL,
    "Description" text DEFAULT 'Description to be added'::text,
    "Rating" real NOT NULL
);


ALTER TABLE public."Hotels" OWNER TO postgres;

--
-- Name: Hotels_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Hotels" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Hotels_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RoomTypes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RoomTypes" (
    "Id" integer NOT NULL,
    "Type" text NOT NULL
);


ALTER TABLE public."RoomTypes" OWNER TO postgres;

--
-- Name: RoomTypes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."RoomTypes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RoomTypes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: HotelOffers; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: HotelReviews; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: HotelRooms; Type: TABLE DATA; Schema: public; Owner: postgres
--


--
-- Data for Name: Hotels; Type: TABLE DATA; Schema: public; Owner: postgres
--


--
-- Data for Name: RoomTypes; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

--
-- Name: HotelReviews_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."HotelReviews_Id_seq"', 1, false);


--
-- Name: HotelRooms_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."HotelRooms_Id_seq"', 1, false);


--
-- Name: Hotels_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Hotels_Id_seq"', 1, false);


--
-- Name: RoomTypes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."RoomTypes_Id_seq"', 1, false);


--
-- Name: HotelOffers PK_HotelOffers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelOffers"
    ADD CONSTRAINT "PK_HotelOffers" PRIMARY KEY ("Id");


--
-- Name: HotelReviews PK_HotelReviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelReviews"
    ADD CONSTRAINT "PK_HotelReviews" PRIMARY KEY ("Id");


--
-- Name: HotelRooms PK_HotelRooms; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelRooms"
    ADD CONSTRAINT "PK_HotelRooms" PRIMARY KEY ("Id");


--
-- Name: Hotels PK_Hotels; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Hotels"
    ADD CONSTRAINT "PK_Hotels" PRIMARY KEY ("Id");


--
-- Name: RoomTypes PK_RoomTypes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RoomTypes"
    ADD CONSTRAINT "PK_RoomTypes" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_HotelOffers_HotelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_HotelOffers_HotelId" ON public."HotelOffers" USING btree ("HotelId");


--
-- Name: IX_HotelOffers_HotelRoomId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_HotelOffers_HotelRoomId" ON public."HotelOffers" USING btree ("HotelRoomId");


--
-- Name: IX_HotelReviews_HotelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_HotelReviews_HotelId" ON public."HotelReviews" USING btree ("HotelId");


--
-- Name: IX_HotelRooms_HotelId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_HotelRooms_HotelId" ON public."HotelRooms" USING btree ("HotelId");


--
-- Name: IX_HotelRooms_RoomTypeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_HotelRooms_RoomTypeId" ON public."HotelRooms" USING btree ("RoomTypeId");


--
-- Name: HotelOffers FK_HotelOffers_HotelRooms_HotelRoomId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelOffers"
    ADD CONSTRAINT "FK_HotelOffers_HotelRooms_HotelRoomId" FOREIGN KEY ("HotelRoomId") REFERENCES public."HotelRooms"("Id") ON DELETE CASCADE;


--
-- Name: HotelOffers FK_HotelOffers_Hotels_HotelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelOffers"
    ADD CONSTRAINT "FK_HotelOffers_Hotels_HotelId" FOREIGN KEY ("HotelId") REFERENCES public."Hotels"("Id") ON DELETE CASCADE;


--
-- Name: HotelReviews FK_HotelReviews_Hotels_HotelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelReviews"
    ADD CONSTRAINT "FK_HotelReviews_Hotels_HotelId" FOREIGN KEY ("HotelId") REFERENCES public."Hotels"("Id") ON DELETE CASCADE;


--
-- Name: HotelRooms FK_HotelRooms_Hotels_HotelId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelRooms"
    ADD CONSTRAINT "FK_HotelRooms_Hotels_HotelId" FOREIGN KEY ("HotelId") REFERENCES public."Hotels"("Id") ON DELETE CASCADE;


--
-- Name: HotelRooms FK_HotelRooms_RoomTypes_RoomTypeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."HotelRooms"
    ADD CONSTRAINT "FK_HotelRooms_RoomTypes_RoomTypeId" FOREIGN KEY ("RoomTypeId") REFERENCES public."RoomTypes"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

