export const ADD_CART_ITEM = "ADD_CART_ITEM"
export const REMOVE_CART_ITEM = "ADD_CART_ITEM"
export const UPDATE_CART_ITEM = "ADD_CART_ITEM"
export const SUBMIT_CART_RESERVATION ="SUBMIT_CART_RESERVATION"

